// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvTrgjpEebQ5zrbbOx7j6CixIzB-_WA5Q',
    appId: '1:880723366597:web:f318c347d3cb625b2bd6ac',
    messagingSenderId: '880723366597',
    projectId: 'smarthomeapp-1a45c',
    authDomain: 'smarthomeapp-1a45c.firebaseapp.com',
    storageBucket: 'smarthomeapp-1a45c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1rnvNKCrxdYlCM-WSsoqr7fkzk8-LeR8',
    appId: '1:880723366597:android:688638c4cfc137bc2bd6ac',
    messagingSenderId: '880723366597',
    projectId: 'smarthomeapp-1a45c',
    storageBucket: 'smarthomeapp-1a45c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAG0s8aJDikbNNdMGuuO5iZDgQKUyswMzQ',
    appId: '1:880723366597:ios:022f4f262ca9a9952bd6ac',
    messagingSenderId: '880723366597',
    projectId: 'smarthomeapp-1a45c',
    storageBucket: 'smarthomeapp-1a45c.firebasestorage.app',
    iosBundleId: 'com.example.smartHomeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAG0s8aJDikbNNdMGuuO5iZDgQKUyswMzQ',
    appId: '1:880723366597:ios:022f4f262ca9a9952bd6ac',
    messagingSenderId: '880723366597',
    projectId: 'smarthomeapp-1a45c',
    storageBucket: 'smarthomeapp-1a45c.firebasestorage.app',
    iosBundleId: 'com.example.smartHomeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvTrgjpEebQ5zrbbOx7j6CixIzB-_WA5Q',
    appId: '1:880723366597:web:58ae4820c64dffb42bd6ac',
    messagingSenderId: '880723366597',
    projectId: 'smarthomeapp-1a45c',
    authDomain: 'smarthomeapp-1a45c.firebaseapp.com',
    storageBucket: 'smarthomeapp-1a45c.firebasestorage.app',
  );
}
